# Server settings
server.port=8080

# Spring DataSource Settings (H2 In-Memory DB for development/testing ease)
spring.datasource.url=jdbc:h2:mem:teamupdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# H2 Console Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA/Hibernate configurations
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# SQL initialization (data.sql seeding)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

# JWT Properties
# 256-bit Hex Encoded Key
teamup.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
teamup.jwt.expiration=86400000

# File Upload / Multipart Settings
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
